### ISSUE TITLE
no interaction between server and device

### ISSUE THREAD

**Issue by BillBridge** [moses-palmer/virtual-touchpad#2]
Hi Moses,

nice application ..... I think when it works.
Am running Python 2.7.
Installation: no problems.
Starting the server: no problem.
Connecting from iphone 6 (iOs 9.3.1) using Chrome: no problem
But no interaction. Not on the touchpad or on  the buttons.

**Comment by moses-palmer** [comment]
Hi Bill,

Thank you for the report.

On what system do you run the server? Do you get any messages in the
console? Does the keyboard work?

I am currently looking into some issues on Windows 10, but that only
affects clicks. Your issue might be caused by JavaScript issues, since all
interaction seems to be missing.

**Comment by BillBridge** [comment]
Hi Moses,

Thanks for your quick reply.
I am running Windows 7 professional.
I do not get any messages on the console. After start of the server the command prompt is not available. The server process keeps running in foreground (on purpose?) and hides any further interaction from the console.

Best regards,
Bill


> Op 8 apr. 2016 om 08:10 heeft moses-palmer <notifications@github.com> het volgende geschreven:
> 
> Hi Bill,
> 
> Thank you for the report.
> 
> On what system do you run the server? Do you get any messages in the
> console? Does the keyboard work?
> 
> I am currently looking into some issues on Windows 10, but that only
> affects clicks. Your issue might be caused by JavaScript issues, since all
> interaction seems to be missing.

**Comment by moses-palmer** [comment]
I just tested with Safari on iOS, and I can confirm that I get the same
behaviour. This is a JavaScript issue on that platform.

I will troubleshoot later today and try to locate the exact cause.

**Comment by moses-palmer** [comment]
I have made a new release, _0.15.1_, which corrects this problem.

_iOS_ does not support _HTML5 Fullscreen_, and _Virtual Touchpad_ required that feature to be present. It did not, however, display a notification about this. I hade added handlers for some missing features, as well as made _HTML5 Fullscreen_ optional.

Please test the new release to verify that it solves the problem for you as well!

**Comment by BillBridge** [comment]
Hi Mo 

I have tested this and the mouse-movements work. Mouse presses do not work (tap on the screen?). 

Best regards, 

----- Oorspronkelijk bericht -----

Van: "moses-palmer" <notifications@github.com> 
Aan: "moses-palmer/virtual-touchpad" <virtual-touchpad@noreply.github.com> 
Cc: "BillBridge" <wimvdb@online.nl> 
Verzonden: Zondag 10 april 2016 10:23:42 
Onderwerp: Re: [moses-palmer/virtual-touchpad] no interaction between server and device (#2) 



I have made a new release, 0.15.1 , which corrects this problem. 

iOS does not support HTML5 Fullscreen , and Virtual Touchpad required that feature to be present. It did not, however, display a notification about this. I hade added handlers for some missing features, as well as made HTML5 Fullscreen optional. 

Please test the new release to verify that it solves the problem for you as well!

**Comment by moses-palmer** [comment]
Hi,

I have confirmed this issue is not limited to Windows 10. The cause was
something akin to a typo in a dependency.

I have corrected the issue upstream and made a new release of both the
dependency and Virtual Touchpad. You only need to update the library pynput.
On 11 Apr 2016 8:10 a.m., "BillBridge" <notifications@github.com> wrote:

Hi Mo

I have tested this and the mouse-movements work. Mouse presses do not work
(tap on the screen?).

Best regards,

----- Oorspronkelijk bericht -----

Van: "moses-palmer" <notifications@github.com>
Aan: "moses-palmer/virtual-touchpad" <virtual-touchpad@noreply.github.com>
Cc: "BillBridge" <wimvdb@online.nl>
Verzonden: Zondag 10 april 2016 10:23:42
Onderwerp: Re: [moses-palmer/virtual-touchpad] no interaction between
server and device (#2)



I have made a new release, 0.15.1 , which corrects this problem.

iOS does not support HTML5 Fullscreen , and Virtual Touchpad required that
feature to be present. It did not, however, display a notification about
this. I hade added handlers for some missing features, as well as made
HTML5 Fullscreen optional.

Please test the new release to verify that it solves the problem for you as
well!

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub

—
You are receiving this because you commented.

Reply to this email directly or view it on GitHub
<https://github.com/moses-palmer/virtual-touchpad/issues/2#issuecomment-208177743>

**Comment by BillBridge** [comment]
Hi Moses, 

I have tried to test it but did not work either. Now there was no connection between server and client. 

Sorry, but I stop testing with it...... 

Best regards, 
Bill 

----- Oorspronkelijk bericht -----

Van: "moses-palmer" <notifications@github.com> 
Aan: "moses-palmer/virtual-touchpad" <virtual-touchpad@noreply.github.com> 
Cc: "BillBridge" <wimvdb@online.nl> 
Verzonden: Maandag 11 april 2016 11:37:54 
Onderwerp: Re: [moses-palmer/virtual-touchpad] no interaction between server and device (#2) 

Hi, 

I have confirmed this issue is not limited to Windows 10. The cause was 
something akin to a typo in a dependency. 

I have corrected the issue upstream and made a new release of both the 
dependency and Virtual Touchpad. You only need to update the library pynput. 
On 11 Apr 2016 8:10 a.m., "BillBridge" <notifications@github.com> wrote: 

Hi Mo 

I have tested this and the mouse-movements work. Mouse presses do not work 
(tap on the screen?). 

Best regards, 

----- Oorspronkelijk bericht ----- 

Van: "moses-palmer" <notifications@github.com> 
Aan: "moses-palmer/virtual-touchpad" <virtual-touchpad@noreply.github.com> 
Cc: "BillBridge" <wimvdb@online.nl> 
Verzonden: Zondag 10 april 2016 10:23:42 
Onderwerp: Re: [moses-palmer/virtual-touchpad] no interaction between 
server and device (#2) 



I have made a new release, 0.15.1 , which corrects this problem. 

iOS does not support HTML5 Fullscreen , and Virtual Touchpad required that 
feature to be present. It did not, however, display a notification about 
this. I hade added handlers for some missing features, as well as made 
HTML5 Fullscreen optional. 

Please test the new release to verify that it solves the problem for you as 
well! 

— 
You are receiving this because you authored the thread. 
Reply to this email directly or view it on GitHub 

— 
You are receiving this because you commented. 

Reply to this email directly or view it on GitHub 
<https://github.com/moses-palmer/virtual-touchpad/issues/2#issuecomment-208177743>
